<h1 class="title">Terms of Service</h1>
<h3 style="margin-top:0;">Conditions relating to use of Nanoflip</h3>
<p>No individual under the age of eighteen (18) may use Nanoflip, regardless of any consent from a parent or guardian to use Nanoflip.</p>
<p>You need a supported Web browser to access Nanoflip. You acknowledge and agree that Nanoflip may cease to support a given Web browser and that your continuous use of Nanoflip will require you to download a supported Web browser. You also acknowledge and agree that the performance of Nanoflip is incumbent on the performance of your computer equipment and your Internet connection.</p>
<p>You agree to sign on and register for Nanoflip through your Steam account provided by Valve Corporation. You are solely responsible for managing your account and password and for keeping your password confidential. You are also solely responsible for restricting access to your account.</p>
<p>You agree that you are responsible for all activities that occur on your account or through the use of your password by yourself or by other persons. If you believe that a third party has access your password, use the password regeneration feature of Nanoflip as soon as possible to obtain a new password. In all circumstances, you agree not to permit any third party to use or access Nanoflip.</p>
<p>As a condition to your use of Nanoflip, you agree not to:</p>
<p>(a) impersonate or misrepresent your affiliation with any person or entity;</p>
<p>(b) access, tamper with, or use any non-public areas of Nanoflip or Nanoflip's computer systems;</p>
<p>(c) attempt to probe, scan, or test the vulnerability of Nanoflip or any related system or network or breach any security or authentication measures used in connection with Nanoflip and such systems and networks;</p>
<p>(d) attempt to decipher, decompile, disassemble, reverse engineer or otherwise investigate any of the software or components used to provide Nanoflip;</p>
<p>(e) harm or threaten to harm other users in any way or interfere with, or attempt to interfere with, the access of any user, host or network, including without limitation, by sending a virus, overloading, flooding, spamming, or mail-bombing Nanoflip;</p>
<p>(f) provide payment information belonging to a third party;</p>
<p>(g) use Nanoflip in an abusive way contrary to its intended use, to Nanoflip's policies and instructions and to any applicable law;</p>
<p>(h) systematically retrieve data or other content from Nanoflip to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, or spiders, or otherwise;</p>
<p>(i) make use of Nanoflip in a manner contrary to the terms and conditions under which third parties provide facilities and technology necessary for the operation of Nanoflip, such as SKFPAY or VALVE CORP;</p>
<p>(j) infringe third party intellectual property rights when using or accessing Nanoflip, including but not limited to in making available virtual items by using Nanoflip;</p>
<p>and (k) make use of, promote, link to or provide access to materials deemed by Nanoflip at its sole discretion to be offensive or cause harm to Nanoflip’s reputation, including, but not limited to, illegal content and pornographic content and content deemed offensive or injurious to Nanoflip (such as Warez sites, IRC bots and bittorent sites).</p>
<h3>Termination</h3>
<p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms of Service.</p>
<p>All provisions of the Terms of Service which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
<p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms of Service.</p>
<p>Upon termination, your right to use Nanoflip will immediately cease. If you wish to terminate your account, you may simply do so by discontinuing your use of Nanoflip.</p>
<h3>Links To Other Web Sites</h3>
<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by Nanoflip.</p>
<p>Nanoflip has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Nanoflip shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>
<h3>No warranties</h3>
<p>This website is provided “as is” without any representations or warranties, express or implied. www.Nanoflip.com makes no representations or warranties in relation to this website or the information and materials provided on this website. Without prejudice to the generality of the foregoing paragraph, www.Nanoflip.com does not warrant that: this website will be constantly available, or available at all; or the information on this website is complete, true, accurate or non-misleading. Nothing on this website constitutes, or is meant to constitute, advice of any kind. If you require advice in relation to any legal, financial or medical matter you should consult an appropriate professional.</p>
<h3>Affiliation</h3>
<p>We are in NO WAY affiliated with or endorsed by the Valve corporation, Counter Strike: Global Offensive, Steam or any other trademarks of the Valve corporation.</p>
<h3>Nanoflip Wallet</h3>
<p>By topping up an amount to your Nanoflip wallet, you accept that the credits received (labeled by the $-sign) are not worth real money and not subject to any refunds.</p>
<h3>Returns and Refunds Policy</h3>
<p>We do not issue refunds for digital products once the order is confirmed and the product is sent. We recommend contacting us for assistance if you experience any issues receiving or downloading our products.</p>
<h3>UI / Interface errors</h3>
<p>Interfaces glitches/manipulation in no way entitles the user to a certain item. All outcomes are generated by our provably fair system and awarded as such. The user agrees that the outcome will be determined by the provably fair system outcome and any user interface errors do not entitle the user to that item.</p>
<h3>Suspicious activity</h3>
<p>If we identify suspicious activity such as using more than 1 e-mail with your account, using an invalid account or clonned credit card, we may ask you to provide documents to confirm authenticity of your account before we clear your purchases.</p>
<h3>Bots and Steam API</h3>
<p>The trade offer request sent by our bots are subject to Steam Guard authentication and the buyer must have Steam Guard activated for at least 15 days on their smartphone so the trade is completed. Note that this is a Steam restriction. The skins won't expire but the user need to wait for that period to end.</p>
<h3>Additional Terms and Conditions; EULAs Part I</h3>
<p>When you use SKFPAY services provided by SKFPAY to make a purchase on our website, responsibility over your purchase will first be transferred to SKFPAY.COM before it is delivered to you. SKFPAY.COM services provider assumes primary responsibility, with our assistance, for payment and payment related customer support. The terms between SKFPAY.COM services provider and customers who utilize services of SKFPAY.COM are governed by separate agreements and are not subject to the Terms of Service on this website.</p>
<p>With respect to customers making purchases through SKFPAY.COM OR PAYPAL.COM services provider checkout, (i) the Privacy Policy of SKFPAY.COM or PAYPAL.COM services provider shall apply to all payments and should be reviewed before making any purchase, and (ii) the SKFPAY.COM or PAYPAL.COM services provider Refund Policy shall apply to all payments unless notice is expressly provided by the relevant supplier to buyers in advance. In addition the purchase of certain products may also require shoppers to agree to one or more End-User License Agreements (or "EULAs") that may include additional terms set by the product supplier rather than by Us, SKFPAY.COM or PAYPAL.COM services provider. You will be bound by any EULA that you agree to.</p>
<p>We and/or entities that sell products on our website by using SKFPAY.COM or PAYPAL.COM services are primarily responsible for warranty, maintenance, technical or product support services for those Products. We and/or entities that sell products on our website are primarily responsible to users for any liabilities related to fulfillment of orders, and EULAs entered into by the End-User Customer. SKFPAY.COM or PAYPAL.COM services provider is primarily responsible for facilitating your payment.</p>
<p>You are responsible for any fees, taxes or other costs associated with the purchase and delivery of your items resulting from charges imposed by your relationship with payment services providers or the duties and taxes imposed by your local customs officials or other regulatory body.</p>
<p>For customer service inquiries or disputes, You may contact us by email at Nanoflip@gmail.com.</p>
<p>You are responsible for any fees, taxes or other costs associated with the purchase and delivery of your items resulting from charges imposed by your relationship with payment services providers or the duties and taxes imposed by your local customs officials or other regulatory body.</p>
<p>For customer service inquiries or disputes, You may contact us by email at Nanoflip@gmail.com.</p>
<p>Where possible, we will work with You and/or any user selling on our website, to resolve any disputes arising from your purchase.</p>
